name: climtools
channels:
- conda-forge
dependencies:
- python
- netcdf4
- cartopy
- eofs
- matplotlib
- numpy
- scikit-learn
- scipy
- xarray
- dask
- dask-jobqueue
- cfgrib
- xesmf
- cdo
- cdsapi
- python-cdo
- ipykernel
- pip
- pip:
  - -e .
