name: climtools
channels:
- scitools
- conda-forge
- defaults
dependencies:
- netcdf4
- cartopy
- eofs
- matplotlib
- numpy
- scikit-learn
- scipy
- xarray
- cfgrib
- xesmf
- cdo
- cdsapi
- python-cdo
- pip:
  - -e .